### What is Numpy..?
Numerical Python, Its basically a backbone of machine learning, data science and numerical computing in python


### Why Numpy...?

- It's Fast
- Behind the secenes optimizations written in C
- Vectorization via broadcasting ( avoiding loops)
- Backbone of other Python scientific packages

### What are we going to cover...?

- Most useful functions
- NumPy datatypes and attributes (ndarray)
- Creating arrays
- Viewing arrays and Matrices
- Manipulating and comparing arrays
- Sorting arrays
- Use cases

### Where can you get help....?

- Follow along the code
- Try it for yourself
- Serch for it - Stack overflow and SciPy.org
- Try again
- Ask

### Tools you can use in Data Science:
####  Data Analysis
- 1. Problem Defination
- 2. Data
- 3. Evaluation
- 4. Features
##### Here we can use Pandas, Matplotlib, Numpy
#### Machine Learning
- 5.Modelling
- 6 Experiments
##### Here we can use TensorFlow, PyTourch, Scikit Learn, dmlc XGBoost, Catboost

In [1]:
import numpy as np
import pandas as pd

## DataTypes & Attributes

In [2]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [5]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [6]:
a1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [8]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [9]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [10]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [11]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [12]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [13]:
# creating a DataFrame from Numpy array

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

### 2.Creating Arrays

In [14]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [15]:
sample_array.dtype

dtype('int32')

In [16]:
ones = np.ones([3, 3])
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
ones.dtype

dtype('float64')

In [18]:
type(ones)

numpy.ndarray

In [19]:
zeros = np.zeros([2, 3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [21]:
random_array = np.random.randint(1, 10, 5)
random_array

array([6, 4, 1, 2, 1])

In [22]:
random_array1 = np.random.randint(0, 10, size = (3,5))
random_array1

array([[0, 8, 0, 8, 8],
       [0, 9, 5, 6, 6],
       [7, 3, 0, 9, 2]])

In [23]:
random_array1.size

15

In [24]:
random_array1.shape

(3, 5)

In [25]:
random_array_2 = np.random.random((3,2))
random_array_2

array([[0.07124312, 0.10006052],
       [0.5899048 , 0.82318134],
       [0.49396233, 0.65244463]])

In [26]:
random_array_2.shape

(3, 2)

In [27]:
random_array_3 = np.random.rand(3,2)
random_array_3

array([[0.08554587, 0.50606026],
       [0.10036604, 0.40868532],
       [0.31721734, 0.71159213]])

In [28]:
# Psedo-random numbers - we need to use seed for generating the random 
# numbers which are not going to change when you re-execute, so that others also get the same 
# random numbers for the experiment
np.random.seed(seed = 1)
random_array_4 = np.random.random((5,3))
random_array_4

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04],
       [3.02332573e-01, 1.46755891e-01, 9.23385948e-02],
       [1.86260211e-01, 3.45560727e-01, 3.96767474e-01],
       [5.38816734e-01, 4.19194514e-01, 6.85219500e-01],
       [2.04452250e-01, 8.78117436e-01, 2.73875932e-02]])

In [29]:
np.random.seed(seed = 1)
random_array_4 = np.random.random((5,3))
random_array_4

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04],
       [3.02332573e-01, 1.46755891e-01, 9.23385948e-02],
       [1.86260211e-01, 3.45560727e-01, 3.96767474e-01],
       [5.38816734e-01, 4.19194514e-01, 6.85219500e-01],
       [2.04452250e-01, 8.78117436e-01, 2.73875932e-02]])

### 3. Viewing arrays and matrices

In [30]:
np.random.seed(seed =9999)
random_array_4 = np.random.randint(10, size = (5,3))
random_array_4

array([[6, 1, 6],
       [5, 5, 9],
       [6, 8, 0],
       [8, 1, 5],
       [3, 1, 0]])

In [31]:
 np.unique(random_array_4)

array([0, 1, 3, 5, 6, 8, 9])

In [32]:
a1

array([1, 2, 3])

In [33]:
a1[0]

1

In [34]:
a2[0]

array([1. , 2. , 3.3])

In [35]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [37]:
random_array_5 = np.random.randint(10, size = ( 2,3,4,5))

In [38]:
random_array_5

array([[[[6, 4, 4, 6, 8],
         [4, 7, 1, 9, 3],
         [9, 3, 3, 9, 1],
         [8, 9, 0, 3, 5]],

        [[0, 5, 9, 9, 5],
         [0, 3, 6, 0, 9],
         [8, 9, 6, 4, 6],
         [9, 8, 6, 3, 2]],

        [[9, 2, 1, 5, 6],
         [4, 0, 2, 4, 7],
         [6, 8, 1, 0, 6],
         [2, 3, 3, 9, 3]]],


       [[[2, 3, 0, 7, 6],
         [7, 9, 0, 9, 8],
         [4, 1, 1, 2, 1],
         [1, 6, 8, 9, 7]],

        [[9, 3, 6, 6, 9],
         [1, 8, 8, 7, 2],
         [2, 2, 3, 7, 1],
         [8, 3, 4, 9, 4]],

        [[8, 9, 9, 2, 0],
         [6, 4, 6, 7, 9],
         [4, 0, 7, 8, 5],
         [4, 6, 5, 0, 0]]]])

In [39]:
np.random.seed(0)
random_array_5.shape, random_array_5.ndim

((2, 3, 4, 5), 4)

In [40]:
random_array_5

array([[[[6, 4, 4, 6, 8],
         [4, 7, 1, 9, 3],
         [9, 3, 3, 9, 1],
         [8, 9, 0, 3, 5]],

        [[0, 5, 9, 9, 5],
         [0, 3, 6, 0, 9],
         [8, 9, 6, 4, 6],
         [9, 8, 6, 3, 2]],

        [[9, 2, 1, 5, 6],
         [4, 0, 2, 4, 7],
         [6, 8, 1, 0, 6],
         [2, 3, 3, 9, 3]]],


       [[[2, 3, 0, 7, 6],
         [7, 9, 0, 9, 8],
         [4, 1, 1, 2, 1],
         [1, 6, 8, 9, 7]],

        [[9, 3, 6, 6, 9],
         [1, 8, 8, 7, 2],
         [2, 2, 3, 7, 1],
         [8, 3, 4, 9, 4]],

        [[8, 9, 9, 2, 0],
         [6, 4, 6, 7, 9],
         [4, 0, 7, 8, 5],
         [4, 6, 5, 0, 0]]]])

- Moving form right to left
- ndim 4 = 4 dimetion array 
- 5  = Total numbers columns are 5 in vertical of each array(4X5)                     (6,4,4,6,8)
- 4 = Total number of rows are 4 in horizontal of each array(4X5)               (6,4,9,8)
- 3 = Total number of matics of each group (3 arrays covered with         brackets First letters - 6, 0,9)
- 2 - 3 matrices of 4X5 matrics for 2 times, First letters -             [6,0,9] and [2,9,8]

In [41]:
# Get the first 4 numbers of the inner most array
random_array_5[:2, :3, :4, :5]

array([[[[6, 4, 4, 6, 8],
         [4, 7, 1, 9, 3],
         [9, 3, 3, 9, 1],
         [8, 9, 0, 3, 5]],

        [[0, 5, 9, 9, 5],
         [0, 3, 6, 0, 9],
         [8, 9, 6, 4, 6],
         [9, 8, 6, 3, 2]],

        [[9, 2, 1, 5, 6],
         [4, 0, 2, 4, 7],
         [6, 8, 1, 0, 6],
         [2, 3, 3, 9, 3]]],


       [[[2, 3, 0, 7, 6],
         [7, 9, 0, 9, 8],
         [4, 1, 1, 2, 1],
         [1, 6, 8, 9, 7]],

        [[9, 3, 6, 6, 9],
         [1, 8, 8, 7, 2],
         [2, 2, 3, 7, 1],
         [8, 3, 4, 9, 4]],

        [[8, 9, 9, 2, 0],
         [6, 4, 6, 7, 9],
         [4, 0, 7, 8, 5],
         [4, 6, 5, 0, 0]]]])

#### 

In [42]:
# 66

## Aritmetic Operations

In [43]:
a1

array([1, 2, 3])

In [44]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [45]:
a1 + ones

array([2., 3., 4.])

In [46]:
np.add(a1,ones)

array([2., 3., 4.])

In [47]:
a1 - ones

array([0., 1., 2.])

In [48]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [49]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [50]:
a1 / a2

array([[1.        , 1.        , 0.90909091],
       [0.25      , 0.4       , 0.46153846]])

In [51]:
a1 // a2

array([[1., 1., 0.],
       [0., 0., 0.]])

In [52]:
# a2 * a3

In [53]:
a1 ** 2

array([1, 4, 9])

In [54]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [55]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [56]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [57]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

In [58]:
# 71

## Dot Product example(nut butter sales)

In [59]:
np.random.seed(0)
# Number of jars sold
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts


array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [60]:
type(sales_amounts)

numpy.ndarray

In [61]:
# create weekly sales dataframe
weekly_sales = pd.DataFrame(sales_amounts, 
                            index = ["Mon","Tues","Wed","Thur","Fri"],
                            columns = ["Almond butter","Peanut butter","Cashew butter"])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon              12             15              0
Tues              3              3              7
Wed               9             19             18
Thur              4              6             12
Fri               1              6              7

In [62]:
# Create prices array
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [63]:
# Create butter prices dataframe
butter_prices = pd.DataFrame(prices.reshape(1,3), 
                             index = ["Price"],
                             columns = ["Almond butter","Peanut butter","Cashew butter"])
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [64]:
prices

array([10,  8, 12])

In [65]:
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [66]:
total_sales = prices * sales_amounts
total_sales

array([[120, 120,   0],
       [ 30,  24,  84],
       [ 90, 152, 216],
       [ 40,  48, 144],
       [ 10,  48,  84]])

In [67]:
total_sales = np.sum(total_sales)
total_sales

1210

In [68]:
a1

array([1, 2, 3])

In [69]:
# 72

## COMPARISON OPERATOR

In [70]:
a1

array([1, 2, 3])

In [71]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [72]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [73]:
bool_array = a1 >= a2
bool_array

array([[ True,  True, False],
       [False, False, False]])

In [74]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [75]:
a1 > 5

array([False, False, False])

In [76]:
a1 < 5

array([ True,  True,  True])

In [77]:
a1 == a1

array([ True,  True,  True])

In [78]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

In [79]:
# 73

### 5. Sorting Arrays

In [80]:
random_array = np.random.randint(10, size = (3,5))

In [81]:
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [82]:
random_array.shape

(3, 5)

In [83]:
np.sort(random_array)

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]])

In [84]:
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [85]:
np.argsort(random_array)

array([[2, 3, 0, 1, 4],
       [4, 3, 2, 0, 1],
       [2, 3, 0, 4, 1]], dtype=int64)

In [86]:
a1

array([1, 2, 3])

In [87]:
a1.argsort()  # It returns the indicies of the elements after sort

array([0, 1, 2], dtype=int64)

In [88]:
a5 = np.array([3,1,2])
a5

array([3, 1, 2])

In [89]:
np.sort(a5)

array([1, 2, 3])

In [90]:
np.argsort(a5)

array([1, 2, 0], dtype=int64)

In [91]:
np.argmin(a1)

0

In [92]:
np.argmax(a1)

2

In [93]:
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [94]:
np.argmax(random_array) 

4

In [95]:
np.argmax(random_array, axis = 1) # answer you need to check column wise

array([4, 1, 1], dtype=int64)

In [96]:
np.argmax(random_array, axis = 0) # answer you need to check row wise

array([1, 1, 1, 0, 0], dtype=int64)

In [ ]:
# 74

## 6. Practical Example - Numpy in Action!!!!

In [110]:
from matplotlib.image import imread

In [113]:
swamiji = imread("images/ss.png")
swamiji

array([[[0.7647059, 0.7647059, 0.7647059, 1.       ],
        [0.7647059, 0.7647059, 0.7647059, 1.       ],
        [0.7647059, 0.7647059, 0.7647059, 1.       ],
        ...,
        [0.7647059, 0.7647059, 0.7647059, 1.       ],
        [0.7647059, 0.7647059, 0.7647059, 1.       ],
        [0.7647059, 0.7647059, 0.7647059, 1.       ]],

       [[0.7647059, 0.7647059, 0.7647059, 1.       ],
        [0.7647059, 0.7647059, 0.7647059, 1.       ],
        [0.7647059, 0.7647059, 0.7647059, 1.       ],
        ...,
        [0.7647059, 0.7647059, 0.7647059, 1.       ],
        [0.7647059, 0.7647059, 0.7647059, 1.       ],
        [0.7647059, 0.7647059, 0.7647059, 1.       ]],

       [[0.7647059, 0.7647059, 0.7647059, 1.       ],
        [0.7647059, 0.7647059, 0.7647059, 1.       ],
        [0.7647059, 0.7647059, 0.7647059, 1.       ],
        ...,
        [0.7647059, 0.7647059, 0.7647059, 1.       ],
        [0.7647059, 0.7647059, 0.7647059, 1.       ],
        [0.7647059, 0.7647059, 0.764705

In [114]:
print(type(swamiji))

<class 'numpy.ndarray'>


In [115]:
swamiji.size, swamiji.shape, swamiji.ndim

(6337464, (833, 1902, 4), 3)

In [116]:
swamiji[:5]

array([[[0.7647059, 0.7647059, 0.7647059, 1.       ],
        [0.7647059, 0.7647059, 0.7647059, 1.       ],
        [0.7647059, 0.7647059, 0.7647059, 1.       ],
        ...,
        [0.7647059, 0.7647059, 0.7647059, 1.       ],
        [0.7647059, 0.7647059, 0.7647059, 1.       ],
        [0.7647059, 0.7647059, 0.7647059, 1.       ]],

       [[0.7647059, 0.7647059, 0.7647059, 1.       ],
        [0.7647059, 0.7647059, 0.7647059, 1.       ],
        [0.7647059, 0.7647059, 0.7647059, 1.       ],
        ...,
        [0.7647059, 0.7647059, 0.7647059, 1.       ],
        [0.7647059, 0.7647059, 0.7647059, 1.       ],
        [0.7647059, 0.7647059, 0.7647059, 1.       ]],

       [[0.7647059, 0.7647059, 0.7647059, 1.       ],
        [0.7647059, 0.7647059, 0.7647059, 1.       ],
        [0.7647059, 0.7647059, 0.7647059, 1.       ],
        ...,
        [0.7647059, 0.7647059, 0.7647059, 1.       ],
        [0.7647059, 0.7647059, 0.7647059, 1.       ],
        [0.7647059, 0.7647059, 0.764705

In [117]:
# 75

In [118]:
# 76

In [ ]:
# 80